### ISSUE TITLE
Distributed Computing

### ISSUE THREAD

**Issue by OlafSzmidt** [Todd-Davies/second-year-notes#4]
Possible mistake. I could be wrong though.

Formula on page 4, uses a variable 'p' instead of 'n' as stated above in the sentence:

> The running time of a program executing on n CPU’s, when it runs in t seconds on one cpu is:

The lecture notes use 'p'.

**Comment by Todd-Davies** [comment]
Cheers Olaf.

Feel free to submit your own PR's too ;)
